modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"
issueTrackerURL = "https://github.com/SteveKunG/Indicatia/issues"

[[mods]]
modId = "indicatia"
version = "${version}"
displayName = "Indicatia"
description = "A small quality of life mod!"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/indicatia"
updateJSONURL = "https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/indicatia_version.json"
logoFile = "logo.png"
authors = "SteveKunG"

[[dependencies.indicatia]]
modId = "forge"
mandatory = true
versionRange = "[46.0.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.indicatia]]
modId = "cloth_config"
mandatory = true
versionRange = "[11.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.indicatia]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "CLIENT"