plugins {
    id "architectury-plugin" version "3.5-SNAPSHOT"
    id "com.gradleup.shadow" version "9.4.2" apply false
    id "dev.architectury.loom-no-remap" version "1.14-SNAPSHOT" apply false
    id "io.github.CDAGaming.cursegradle" version "1.6.1" apply false
    id "com.modrinth.minotaur" version "2.+" apply false
}

apply from: "https://raw.githubusercontent.com/SteveKunG/GradleScripts/refs/heads/v2/architectury/main.gradle"