# gradle
java_version=21
use_mixin=true
upload_debug=true

# minecraft
minecraft_version=24w21b
parchmentmc_version=1.20.6:2024.05.01

# mod
display_name=Indicatia
archives_base_name=indicatia
maven_group=com.stevekung.indicatia
mod_version=8.1.2
release_type=release
enabled_platforms=fabric
cloth_config_version=14.0.126
mixinextras_version=0.3.6
mixinsquared_version=0.2.0-beta.3

# curseforge
curseforge_project_id=272146
curseforge_fabric_required_dependencies=fabric-api,cloth-config
curseforge_fabric_optional_dependencies=modmenu
curseforge_forge_required_dependencies=cloth-config
curseforge_neoforge_required_dependencies=cloth-config

# modrinth
modrinth_project_id=indicatia
modrinth_fabric_required_dependencies=fabric-api,cloth-config
modrinth_fabric_optional_dependencies=modmenu
modrinth_forge_required_dependencies=cloth-config
modrinth_neoforge_required_dependencies=cloth-config

# fabric
fabric_loader_version=0.15.11
fabric_api_version=0.99.1+1.21
modmenu_version=10.0.0-beta.1

# forge
forge_version=50.0.25

# neoforge
neoforge_version=20.6.72-beta