# main
mc_version=1.20.4
parchmentmc_version=1.20.4:2024.02.25
enabled_platforms=fabric,forge

# mod
archives_base_name=indicatia
maven_group=com.stevekung.indicatia
mod_version=8.1.2
mixinextras_version=0.3.5
mixinsquared_version=0.1.2-beta.4

# fabric
fabric_loader_version=0.15.7
fabric_api_version=0.96.0+1.20.4
modmenu_version=9.0.0
cloth_config_version=13.0.121

# forge
forge_version=49.0.31

# neoforge
neoforge_version=20.4.190