apply from: "https://raw.githubusercontent.com/SteveKunG/GradleScripts/main/architectury/common.gradle"

dependencies {
    implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:${mixinsquared_version}"))
    implementation("me.fallenbreath:conditional-mixin-fabric:${conditional_mixin_version}") {
        exclude group: "net.fabricmc", module: "fabric-loader"
    }
}