modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/SteveKunG/Indicatia/issues"

[[mods]]
modId = "indicatia"
version = "${version}"
displayName = "Indicatia"
description = "A small quality of life mod!"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/indicatia"
updateJSONURL = "https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/indicatia_version.json"
logoFile = "logo.png"
authors = "SteveKunG"
displayTest = "IGNORE_SERVER_VERSION"

[[mixins]]
config = "mixins.indicatia.json"
[[mixins]]
config = "mixins.indicatia_neoforge.json"

[[dependencies.indicatia]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.indicatia]]
modId = "cloth_config"
mandatory = true
versionRange = "[12.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.indicatia]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "CLIENT"