modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
issueTrackerURL = "https://github.com/SteveKunG/Indicatia/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${display_name}"
description = "${mod_description}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/indicatia"
updateJSONURL = "https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/indicatia_version.json"
logoFile = "logo.png"
authors = "SteveKunG"
displayTest = "IGNORE_SERVER_VERSION"

[[mixins]]
config = "mixins.indicatia.json"
[[mixins]]
config = "mixins.indicatia_neoforge.json"

[[dependencies.indicatia]]
modId = "neoforge"
type = "required"
versionRange = "[21.6,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.indicatia]]
modId = "cloth_config"
type = "required"
versionRange = "[19.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.indicatia]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.6,)"
ordering = "NONE"
side = "CLIENT"