apply from: "https://raw.githubusercontent.com/SteveKunG/GradleScripts/refs/heads/v2/architectury/neoforge.gradle"

loom {
    runs.configureEach {
        properties project.commonProperties
        vmArgs project.commonVmArgs
        vmArgs project.hotswapVmArgs
    }

    runs {
        client {
            if (project.hasProperty("usernameAndUUID")) {
                programArgs project.usernameAndUUID
            }
        }
        server {
            ideConfigGenerated = false
        }
    }
}

String fileName = "${archives_base_name}-mc${minecraft_version}"

shadowJar {
    dependsOn jar
    mainSpec.sourcePaths.clear()       // Remove default source set inclusion
    from zipTree(jar.archiveFile)     // Unpack jar output (preserves Loom modifications)

    configurations = [project.configurations.shadowBundle]
    archiveClassifier = "neoforge" + (release_type != "release" ? "-${release_type}" : "")
    archiveVersion = "v${mod_version}"
    archiveBaseName = fileName
}

sourcesJar {
    Jar commonSources = project(":common").sourcesJar
    dependsOn commonSources
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from commonSources.archiveFile.map { zipTree(it) }
    archiveVersion = "v${mod_version}"
    archiveBaseName = fileName
}